name: docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to docker hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Build and push docker image
        uses: docker/build-push-action@v6.7.0
        with:
          context: ./docker
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest-${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    container:
      image: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest-${{ github.sha }}
    env:
      DB_HOST: ${{ secrets.TEST_DB_HOST }}
      DB_PORT: ${{ secrets.TEST_DB_PORT }}
      DB_NAME: ${{ secrets.TEST_DB_NAME }}
      DB_USER: ${{ secrets.TEST_DB_USER }}
      DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.TEST_DB_PORT }}
        ports:
          - 5432:5432
    steps:
      - name: Run tests
        working-directory: /app
        run: pytest tests

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Deploy to server
        run: echo "Deploying..."

  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify deployment
        run: echo "Verification..."
