name: docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build images
        run: |
          docker build -t app:latest ./docker/
          docker save -o app-image.tar app:latest

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    container:
      image: app:latest
      env:
        DB_HOST: ${{ secrets.TEST_DB_HOST }}
        DB_PORT: ${{ secrets.TEST_DB_PORT }}
        DB_NAME: ${{ secrets.TEST_DB_NAME }}
        DB_USER: ${{ secrets.TEST_DB_USER }}
        DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.TEST_DB_PORT }}
        ports:
          - 5432:5432
    steps:
      - name: Run tests
        run: pytest docker/tests/

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Deploy to server
        run: echo "Deploying..."

  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify deployment
        run: echo "Verification..."
