name: docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build images
        run: |
          docker build -t app:latest ./docker/

  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    container:
      image: docker.io/library/app:latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: kubsu
          POSTGRES_PASSWORD: kubsu
          POSTGRES_PORT: 5432
          POSTGRES_USER: kubsu
        ports:
          - 5432:5432
    steps:
      - name: Run tests
        run: pytest docker/tests/

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Deploy to server
        run: echo "Deploying..."

  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Verify deployment
        run: echo "Verification..."
